using Roboto.Migrator;

// dotnet run --project src/Roboto.Migrator -- <xmlPath> <dataDir> <instance> [--dry-run] [--carry-steam-key]
//
// A separate console tool, not a Telegram command and not part of Roboto.Bot's always-running
// host - structurally impossible to trigger via a chat message. See MIGRATION.md's phase 11
// section for the full safety rationale (never touches the source XML in place, never writes
// telegramAPIKey anywhere, dry-run/checksum validation before any real write, timestamps reset to
// import time, resumed pending replies written undelivered - never sent live by this tool).

if (args.Length < 3)
{
    Console.Error.WriteLine("Usage: Roboto.Migrator <xmlPath> <dataDir> <instance> [--dry-run] [--carry-steam-key]");
    return 1;
}

var options = new ImportOptions(
    XmlPath: args[0],
    DataDir: args[1],
    Instance: args[2],
    DryRun: args.Contains("--dry-run"),
    CarrySteamKey: args.Contains("--carry-steam-key"));

if (!File.Exists(options.XmlPath))
{
    Console.Error.WriteLine($"No such file: {options.XmlPath}");
    return 1;
}

Console.WriteLine($"Importing {options.XmlPath} -> {options.DataDir}/{options.Instance}" + (options.DryRun ? " (DRY RUN - no real write)" : ""));

var result = await new XmlImporter().RunAsync(options, CancellationToken.None);

Console.WriteLine();
Console.WriteLine(result.Report.ToString());
Console.WriteLine();

if (options.DryRun)
{
    Console.WriteLine("Dry run complete - nothing was written to the target instance.");
    return 0;
}

// TelegramToken is never written here, under any circumstance - the real production token must
// never pass through this tool. The user fills it in themselves, directly wherever the instance
// actually runs, exactly matching InstanceBootstrapper's existing "blank stub, fill in and
// restart" convention (src/Roboto.Bot/InstanceBootstrapper.cs).
var botEnvPath = Path.Combine(options.DataDir, options.Instance, "bot.env");
var botEnvLines = new List<string>
{
    "# Generated by Roboto.Migrator - fill in TelegramToken (never written by the importer) and restart.",
    "TelegramToken=",
    $"BotUsername={result.LegacyBotUserName}",
    "",
};

if (result.SteamApiKeyToCarry is not null)
{
    botEnvLines.Add("SteamApiKey=" + result.SteamApiKeyToCarry);
}
else
{
    botEnvLines.Add("# SteamApiKey= (not carried - pass --carry-steam-key to include it, if the source had one)");
}

await File.WriteAllLinesAsync(botEnvPath, botEnvLines);
Console.WriteLine($"Wrote {botEnvPath} (TelegramToken left blank - fill it in before starting this instance).");

return 0;
